/**
 * Drift guard for FailproofAI Cloud's port of the CLI's Jev decision path
 * (CONTRACT C10.4, review M2).
 *
 * FailproofAI Cloud selects, compiles and decides its Jev checks with a Rust
 * port of `selectPolicies`, `compileRequest`'s per-policy questions,
 * `questionChars`, `scanTargets` and `decide` / `decideV1` (agenteye
 * `server/src/jev_select.rs`, `jev_decide.rs`, `jev_cloud.rs`). The port is
 * pinned there by three fixtures generated by RUNNING this TypeScript. Their
 * copies here are replayed through the CURRENT TypeScript: any behaviour change
 * to that path fails this file, so it cannot drift from Cloud silently.
 *
 * The fixtures here and in agenteye `server/tests/fixtures/cloud_jev/` are
 * byte-identical copies (see `__tests__/fixtures/cloud-jev/README.md`).
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { isDeepStrictEqual } from "node:util";
import { describe, expect, it } from "vitest";
import { parsePackSemanticPolicy } from "@/src/hooks/pack-manifest";
import { compileRequest, DEFAULT_JEV_MODEL, selectPolicies } from "@/src/hooks/semantic/compile";
import { cloudGlobalQuestions } from "@/src/hooks/semantic/cloud-jev";
import { DEFAULT_THRESHOLDS, DEFAULT_THRESHOLDS_V1, decide, decideV1, scanTargets } from "@/src/hooks/semantic/decide";
import { questionChars, toSemanticPolicy } from "@/src/hooks/semantic/pack-policies";
import { INJECTION_PROBE, SCOPE_PROBE, TASK_PROBES } from "@/src/hooks/semantic/policies";
import type { SemanticManifestEntry } from "@/src/hooks/pack-manifest";
import type { Facts, SemanticPolicy } from "@/src/hooks/semantic/types";

const DIR = resolve(__dirname, "../fixtures/cloud-jev");

const DRIFT =
  "The CLI's Jev decision path no longer reproduces the FailproofAI Cloud parity fixtures. Cloud decides its " +
  "Jev checks with a Rust port of this code (agenteye server/src/jev_select.rs, jev_decide.rs, jev_cloud.rs). " +
  "If the change is intended, in the SAME change: regenerate with " +
  "__tests__/fixtures/cloud-jev/generators/run.sh, copy decide-parity.json, compile-parity.json and " +
  "select-parity.json byte for byte into agenteye server/tests/fixtures/cloud_jev/ (the server's copies must be " +
  "regenerated too), update the sha256 pins in both repos, and port the change to the Rust.";

/**
 * The fixtures' sha256, pinned identically in agenteye `server/src/jev_select.rs`
 * (`fixture_copies_match_the_cli_repo`). A regeneration changes them: update both repos.
 */
const FIXTURE_SHA256: Record<string, string> = {
  "decide-parity.json": "1b38d72111e8861ee7c8ff0963b32936c57bcd3505ff0ec46722920dba1c0140",
  "compile-parity.json": "a3cf1194ae5b09c8a4ffbbc4515b1a7f4bd27ef317921ff7b788602c0e20c998",
  "select-parity.json": "4231c78e435959d989181e2272a3c447af4f4264e31e45a537b9a45a3525a933",
};

const load = (file: string): any => JSON.parse(readFileSync(`${DIR}/${file}`, "utf8"));
const DECIDE = load("decide-parity.json");
const COMPILE = load("compile-parity.json");
const SELECT = load("select-parity.json");

/** As the generator converts a declaration: `toSemanticPolicy`, minus `origin` (attribution only). */
function policyOf(decl: SemanticManifestEntry): SemanticPolicy {
  const { origin: _origin, ...policy } = toSemanticPolicy(decl, { id: "cloud" });
  void _origin;
  return policy;
}
const POLICIES = new Map<string, SemanticPolicy>(
  Object.values(DECIDE.declarations as Record<string, SemanticManifestEntry>).map((d) => [d.name, policyOf(d)]),
);

const json = (v: unknown): unknown => JSON.parse(JSON.stringify(v));
const serializeScan = (scan: ReturnType<typeof scanTargets>) => ({
  groups: scan.groups.map((g) => [...g].sort()),
  complete: scan.complete,
});

/** Every case run through `run`; the ids of those that no longer match, with the first one shown whole. */
function replay(what: string, cases: any[], run: (c: any) => unknown, expected: (c: any) => unknown): void {
  const bad: Array<{ id: string; got: unknown; want: unknown }> = [];
  for (const c of cases) {
    const got = json(run(c));
    const want = expected(c);
    if (!isDeepStrictEqual(got, want)) bad.push({ id: c.id ?? `${c.name}/${c.intentMode}/${c.userSaidNonEmpty}`, got, want });
  }
  const first = bad[0] ? `\nfirst: ${bad[0].id}\n got ${JSON.stringify(bad[0].got).slice(0, 1500)}\nwant ${JSON.stringify(bad[0].want).slice(0, 1500)}` : "";
  expect(bad.map((b) => b.id), `${DRIFT}\n${what}: ${bad.length} of ${cases.length} cases differ${first}`).toEqual([]);
}

describe("FailproofAI Cloud Jev parity fixtures replay through the current CLI (review M2)", () => {
  it("are the copies agenteye pins, and cover what they claim", () => {
    for (const [file, sha] of Object.entries(FIXTURE_SHA256)) {
      const got = createHash("sha256").update(readFileSync(`${DIR}/${file}`)).digest("hex");
      expect(got, `${file} is not the copy agenteye pins. ${DRIFT}`).toBe(sha);
    }
    expect(DECIDE.cases.length).toBeGreaterThanOrEqual(2_000);
    expect(COMPILE.cases.length).toBeGreaterThanOrEqual(224);
    expect(SELECT.cases.length).toBeGreaterThanOrEqual(480);
    // One declarations table across the three files.
    expect(COMPILE.declarations).toEqual(DECIDE.declarations);
    expect(SELECT.declarations).toEqual(DECIDE.declarations);
  });

  it("thresholds are the ones Cloud hard-codes", () => {
    expect(json({ v0: DEFAULT_THRESHOLDS, v1: DEFAULT_THRESHOLDS_V1 }), DRIFT).toEqual(DECIDE.thresholds);
  });

  it("every declaration is what the CLI's parser makes of it", () => {
    const decls = Object.values(DECIDE.declarations) as unknown[];
    replay(
      "parsePackSemanticPolicy",
      decls.map((d: any, i) => ({ id: d.name, d, i })),
      (c) => parsePackSemanticPolicy("cloud", c.d, c.i),
      (c) => c.d,
    );
  });

  it("scanTargets gives every case's targetScan", () => {
    replay("scanTargets", DECIDE.cases, (c) => serializeScan(scanTargets(c.toolInput)), (c) => c.targetScan);
  });

  it("decide (v0) and decideV1 (v1) give every case's verdict: decision, reason and outcomes", () => {
    replay(
      "decide/decideV1",
      DECIDE.cases,
      (c) => {
        const selected = (c.policies as string[]).map((n) => POLICIES.get(n)!);
        return c.intentMode === "v1"
          ? decideV1(selected, c.answers, c.toolInput, c.userSaid, c.agentLastMessage, { userSaidCut: c.userSaidCut })
          : decide(selected, c.answers, c.toolInput, c.userSaid, DEFAULT_THRESHOLDS, c.userSaidCut);
      },
      (c) => c.expected,
    );
  });

  it("compileRequest gives every declaration's per-policy questions, in order, and the globals it adds", () => {
    const GLOBAL = new Set(globalIds());
    replay(
      "compileRequest",
      COMPILE.cases,
      (c) => {
        const all = compileRequest([POLICIES.get(c.name)!], {}, c.userSaidNonEmpty ? ["please do it"] : [], DEFAULT_JEV_MODEL, c.intentMode)
          .request.questions;
        const questions = Object.fromEntries(Object.entries(all).filter(([k]) => !GLOBAL.has(k)));
        return {
          questions,
          keys: Object.keys(questions),
          chars: JSON.stringify(questions).length,
          globals: Object.keys(all).filter((k) => GLOBAL.has(k)),
        };
      },
      (c) => ({ questions: c.questions, keys: c.keys, chars: c.chars, globals: c.globals }),
    );
  });

  it("questionChars (the budget measure) gives every declaration's count", () => {
    const decls = Object.values(DECIDE.declarations) as SemanticManifestEntry[];
    replay(
      "questionChars",
      decls.map((d) => ({ id: d.name, d })),
      (c) => questionChars(c.d),
      (c) => COMPILE.questionChars[c.id],
    );
  });

  it("selectPolicies gives every case's selection, in order", () => {
    const ordered = (SELECT.declarationOrder as string[]).map((n) => POLICIES.get(n)!);
    replay("selectPolicies", SELECT.cases, (c) => selectPolicies(ordered, c.facts as Facts).map((p) => p.name), (c) => c.selected);
  });

  it("the global question ids are exactly the ones Cloud treats as global", () => {
    // Cloud's GLOBAL_QUESTION_IDS is pinned to this union in agenteye (jev_cloud.rs).
    const pinned = [...new Set((COMPILE.cases as any[]).flatMap((c) => c.globals as string[]))].sort();
    expect(globalIds().sort(), DRIFT).toEqual(pinned);
    // Every question compileRequest adds that belongs to no policy is one of them…
    const owned = new Set<string>();
    for (const p of POLICIES.values()) {
      for (const intent of ["v0", "v1"] as const) {
        const compiled = compileRequest([p], {}, ["please do it"], DEFAULT_JEV_MODEL, intent);
        for (const [id, owner] of compiled.owners) if (owner === null) owned.add(id);
      }
    }
    expect([...owned].sort(), DRIFT).toEqual(pinned);
    // …and so is every question a Cloud call adds on top of the machine's own.
    const cloud = new Set(
      (["v0", "v1"] as const).flatMap((intent) => [0, 1].flatMap((n) => Object.keys(cloudGlobalQuestions(intent, n)))),
    );
    expect([...cloud].sort(), DRIFT).toEqual(pinned);
  });
});

function globalIds(): string[] {
  return [INJECTION_PROBE.id, SCOPE_PROBE.id, ...TASK_PROBES.map((p) => p.id)];
}
