"""Authoring and worker primitives for FailproofAI Evaluator v2.

This namespace is intentionally lazy relative to :mod:`failproofai_sdk`: users
who only emit telemetry do not import evaluator networking or runtime code.
"""

from failproofai_sdk.evaluator.authoring import (
    Assertion,
    ConditionResult,
    EvalDefinition,
    EvalResult,
    Evaluator,
    Metric,
    Score,
)
from failproofai_sdk.evaluator.client import EvaluatorAPIError, EvaluatorClient
from failproofai_sdk.evaluator.protocol import (
    Assignment,
    CatalogDefinition,
    ClaimRequest,
    ClaimResponse,
    ErrorResponse,
    EvalSelection,
    EvaluatorKind,
    HeartbeatRequest,
    HeartbeatResponse,
    HeartbeatRun,
    PlannedRun,
    PlanRequest,
    PlanResponse,
    ProtocolError,
    RegisterRequest,
    RegisterResponse,
    RemoteError,
    ResultItem,
    ResultKind,
    ResultRequest,
    ResultResponse,
    SessionTranscript,
    SkippedEval,
    TerminalRunStatus,
    TranscriptEvent,
    UnsupportedProtocolVersion,
)
from failproofai_sdk.evaluator.runtime import WorkerConfig, WorkerRuntime

__all__ = [
    "Assertion",
    "Assignment",
    "CatalogDefinition",
    "ClaimRequest",
    "ClaimResponse",
    "ConditionResult",
    "ErrorResponse",
    "EvalDefinition",
    "EvalResult",
    "EvalSelection",
    "Evaluator",
    "EvaluatorAPIError",
    "EvaluatorClient",
    "EvaluatorKind",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "HeartbeatRun",
    "Metric",
    "PlanRequest",
    "PlanResponse",
    "PlannedRun",
    "ProtocolError",
    "RegisterRequest",
    "RegisterResponse",
    "RemoteError",
    "ResultItem",
    "ResultKind",
    "ResultRequest",
    "ResultResponse",
    "Score",
    "SessionTranscript",
    "SkippedEval",
    "TerminalRunStatus",
    "TranscriptEvent",
    "UnsupportedProtocolVersion",
    "WorkerConfig",
    "WorkerRuntime",
]
