"""Authoring and worker primitives for FailproofAI Evaluator v2.

This namespace is intentionally lazy relative to :mod:`failproofai_sdk`: users
who only emit telemetry do not import evaluator networking or runtime code.
"""

from failproofai_sdk.evaluator.authoring import (
    Assertion,
    ConditionResult,
    EvalDefinition,
    EvalResult,
    Evaluator,
    Metric,
    Score,
)
from failproofai_sdk.evaluator.client import EvaluatorAPIError, EvaluatorClient
from failproofai_sdk.evaluator.protocol import (
    Assignment,
    AssignmentDefinition,
    CatalogDefinition,
    ClaimRequest,
    ClaimResponse,
    ErrorResponse,
    EvalSelection,
    ExecutionMode,
    EvaluatorKind,
    HeartbeatRequest,
    HeartbeatResponse,
    HeartbeatRun,
    PlannedRun,
    PlanRequest,
    PlanResponse,
    DefinitionsResponse,
    ProtocolError,
    RegisterRequest,
    RegisterResponse,
    RemoteError,
    ResultItem,
    ResultKind,
    ResultRequest,
    ResultResponse,
    SessionTranscript,
    SkippedEval,
    TerminalRunStatus,
    TranscriptEvent,
    UnsupportedProtocolVersion,
)
from failproofai_sdk.evaluator.runtime import WorkerConfig, WorkerRuntime
from failproofai_sdk.evaluator.source import (
    UnsafeEvaluatorSource,
    compile_condition,
    compile_evaluator,
    source_checksum,
)

__all__ = [
    "Assertion",
    "Assignment",
    "AssignmentDefinition",
    "CatalogDefinition",
    "ClaimRequest",
    "ClaimResponse",
    "ConditionResult",
    "ErrorResponse",
    "EvalDefinition",
    "EvalResult",
    "EvalSelection",
    "ExecutionMode",
    "Evaluator",
    "EvaluatorAPIError",
    "EvaluatorClient",
    "EvaluatorKind",
    "HeartbeatRequest",
    "HeartbeatResponse",
    "HeartbeatRun",
    "Metric",
    "PlanRequest",
    "PlanResponse",
    "DefinitionsResponse",
    "PlannedRun",
    "ProtocolError",
    "RegisterRequest",
    "RegisterResponse",
    "RemoteError",
    "ResultItem",
    "ResultKind",
    "ResultRequest",
    "ResultResponse",
    "Score",
    "SessionTranscript",
    "SkippedEval",
    "TerminalRunStatus",
    "TranscriptEvent",
    "UnsupportedProtocolVersion",
    "WorkerConfig",
    "WorkerRuntime",
    "UnsafeEvaluatorSource",
    "compile_condition",
    "compile_evaluator",
    "source_checksum",
]
