// AUTO-GENERATED by failproofai. __failproofai_hook__
// Re-generate via: failproofai policies --install --cli opencode
//
// DEV variant: this repo's contributors run failproofai from source, via
// the shared `scripts/dev-hook.mjs` resolver rather than `npx -y failproofai`.
// That resolver locates bun across PATH, $BUN_INSTALL/bin, ~/.bun/bin, Homebrew
// and every nvm version dir — a bare `spawnSync("bun")` silently fails open the
// moment bun is off the hook's PATH. The production shape (npx-based) is
// generated by `src/hooks/integrations.ts` on install for end users — see
// `buildOpenCodePluginShim` there.
//
// Do NOT install this repo via `failproofai policies --install --cli
// opencode --scope project` — it would overwrite this dev path with the
// portable npx form.
//
// IMPORTANT: keep TOOL_NAME_MAP / TOOL_INPUT_MAP in sync with both:
//   • src/hooks/types.ts (OPENCODE_TOOL_MAP / OPENCODE_TOOL_INPUT_MAP)
//   • src/hooks/integrations.ts (buildOpenCodePluginShim production template)
// When #337 landed, this dev shim drifted and `block-read-outside-cwd`
// silently no-op'd on every opencode `read` call inside this repo.
import { spawn } from "node:child_process";
import { resolveDevSpawn } from "../../scripts/dev-hook.mjs";

const BUS_EVENT_MAP = {
  "session.created": "SessionStart",
  "session.deleted": "SessionEnd",
  "session.idle":    "Stop",
};

// Map opencode lowercase tool IDs (`input.tool`) → Claude PascalCase canonical
// names. Builtin failproofai policies match on PascalCase via case-sensitive
// `Array.includes`, so without this every Bash/Read/Write/Edit builtin
// silently no-ops under opencode.
const TOOL_NAME_MAP = {
  bash: "Bash",
  read: "Read",
  write: "Write",
  edit: "Edit",
  apply_patch: "Edit",
  glob: "Glob",
  grep: "Grep",
  list: "LS",
  webfetch: "WebFetch",
  websearch: "WebSearch",
  todowrite: "TodoWrite",
  todoread: "TodoRead",
};
function canonicalizeTool(raw) {
  if (!raw) return raw;
  return TOOL_NAME_MAP[raw] != null ? TOOL_NAME_MAP[raw] : raw;
}

// Per-tool input-key translation: opencode native tools deliver args as
// camelCase (`filePath`, `oldString`, …) but failproofai builtin policies
// (`block-read-outside-cwd`, `block-env-files`, `block-secrets-write`)
// read `ctx.toolInput.file_path` etc. Without this map every Read/Write/Edit
// path-check silently no-ops on opencode. Keys are PascalCase canonical tool
// names so the lookup pairs with canonicalizeTool's output.
const TOOL_INPUT_MAP = {
  Read: { filePath: "file_path" },
  Write: { filePath: "file_path" },
  Edit: { filePath: "file_path", oldString: "old_string", newString: "new_string", replaceAll: "replace_all" },
};
function canonicalizeToolInput(canonicalToolName, args) {
  if (!args || typeof args !== "object") return args;
  const map = TOOL_INPUT_MAP[canonicalToolName];
  if (!map) return args;
  const out = {};
  for (const k of Object.keys(args)) out[map[k] != null ? map[k] : k] = args[k];
  return out;
}

/**
 * Run failproofai for one event WITHOUT blocking opencode's event loop.
 *
 * This was `spawnSync`, and opencode loads the plugin in-process in the TUI —
 * so every hook froze rendering and input for the subprocess's full duration,
 * with a 60s ceiling. The verdicts are unchanged: every caller already `await`s
 * `applyDecision`, so the deny still lands before the tool runs. What changes
 * is that the wait is now a promise rather than a blocked thread, and the TUI
 * keeps painting while it happens.
 *
 * Fail-open on spawn error, and on the timeout — a policy that never ran must
 * not read as a deny.
 */
async function runFailproofai(eventName, payload, directory) {
  const resolved = resolveDevSpawn();
  if (!resolved) {
    process.stderr.write(
      "[failproofai-dev] bun not found — opencode policies are NOT enforcing. " +
        "Install bun: curl -fsSL https://bun.sh/install | bash\n",
    );
    return { exitCode: 0, stdout: "", stderr: "" };
  }
  const cmd = resolved.cmd;
  const args = [...resolved.args, "--hook", eventName, "--cli", "opencode"];
  return await new Promise((resolveRun) => {
    let child;
    try {
      child = spawn(cmd, args, { cwd: directory });
    } catch {
      resolveRun({ exitCode: 0, stdout: "", stderr: "" });
      return;
    }
    let stdout = "";
    let stderr = "";
    let settled = false;
    const finish = (exitCode) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolveRun({ exitCode, stdout, stderr });
    };
    const timer = setTimeout(() => {
      try { child.kill("SIGKILL"); } catch { /* already gone */ }
      finish(0);
    }, 60_000);
    child.stdout.on("data", (d) => { stdout += d; });
    child.stderr.on("data", (d) => { stderr += d; });
    child.on("error", () => finish(0));
    child.on("close", (code) => finish(code ?? 0));
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

async function applyDecision(result, ctx, eventName) {
  if (result.exitCode === 2) {
    throw new Error((result.stderr || "").trim() || "Blocked by failproofai");
  }
  let parsed = null;
  try { parsed = JSON.parse(result.stdout); } catch { /* fail-open allow */ }
  if (!parsed) return;
  const out = parsed.hookSpecificOutput;
  if (out && out.permissionDecision === "deny") {
    throw new Error(out.permissionDecisionReason || "Blocked by failproofai");
  }
  if (out && out.decision && out.decision.behavior === "deny") {
    throw new Error((out.decision.message) || "Blocked by failproofai");
  }
  // For Stop / SubagentStop the prompt is the only force-retry channel
  // (session.idle already fired), so AWAIT to ensure the SDK round-trip
  // completes before the plugin handler returns. For tool events keep
  // fire-and-forget so we don't add latency to every tool call.
  const ctxText = out && out.additionalContext;
  if (ctxText && ctx && ctx.client && ctx.sessionID) {
    const prompt = ctx.client.session.prompt({
      path: { id: ctx.sessionID },
      body: { parts: [{ type: "text", text: ctxText }] },
    });
    if (eventName === "Stop" || eventName === "SubagentStop") {
      try { await prompt; } catch { /* swallow — agent is exiting anyway */ }
    } else {
      Promise.resolve(prompt).catch(() => {});
    }
  }
}

export default async function failproofaiPlugin({ client, directory }) {
  return {
    event: async ({ event }) => {
      if (!event || !event.type) return;
      if (event.type === "message.updated") {
        const props = event.properties || {};
        const info = props.info || props.message || {};
        const role = info.role || props.role;
        if (role !== "user") return;
        const sessionID = info.sessionID || info.sessionId || info.session_id || props.sessionID;
        let prompt = "";
        const parts = info.parts || props.parts || [];
        if (Array.isArray(parts)) {
          for (const p of parts) {
            if (p && typeof p === "object" && typeof p.text === "string") prompt += p.text;
          }
        }
        if (!prompt) prompt = (info.text || info.content || props.text || "").toString();
        const r = await runFailproofai("UserPromptSubmit", {
          session_id: sessionID, cwd: directory, hook_event_name: "UserPromptSubmit", prompt,
        }, directory);
        await applyDecision(r, { client, sessionID }, "UserPromptSubmit");
        return;
      }
      const claudeEvent = BUS_EVENT_MAP[event.type];
      if (!claudeEvent) return;
      const props = event.properties || {};
      const sessionID = props.sessionID || (props.session && props.session.id) || props.id;
      const r = await runFailproofai(claudeEvent, {
        session_id: sessionID, cwd: directory, hook_event_name: claudeEvent,
      }, directory);
      await applyDecision(r, { client, sessionID }, claudeEvent);
    },

    "tool.execute.before": async (input, output) => {
      const canonicalTool = canonicalizeTool(input.tool);
      const r = await runFailproofai("PreToolUse", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: canonicalTool,
        tool_input: canonicalizeToolInput(canonicalTool, output.args),
        hook_event_name: "PreToolUse",
      }, directory);
      await applyDecision(r, { client, sessionID: input.sessionID }, "PreToolUse");
    },

    "tool.execute.after": async (input, output) => {
      const canonicalTool = canonicalizeTool(input.tool);
      const r = await runFailproofai("PostToolUse", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: canonicalTool,
        tool_input: canonicalizeToolInput(canonicalTool, input.args),
        tool_response: { title: output.title, output: output.output, metadata: output.metadata },
        hook_event_name: "PostToolUse",
      }, directory);
      await applyDecision(r, { client, sessionID: input.sessionID }, "PostToolUse");
    },

    "permission.ask": async (input, output) => {
      const canonicalTool = canonicalizeTool(input.tool);
      const r = await runFailproofai("PermissionRequest", {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: canonicalTool || input.command || "permission",
        tool_input: canonicalizeToolInput(canonicalTool, input),
        hook_event_name: "PermissionRequest",
      }, directory);
      try {
        await applyDecision(r, { client, sessionID: input.sessionID }, "PermissionRequest");
      } catch {
        output.status = "deny";
      }
    },
  };
}
